import { Link, useParams } from 'react-router-dom';
import { TransactionTimeline } from '@/components/ai/transaction-timeline';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { LogicLabel } from '@/components/ui/logic-label';
import { StatusBadge } from '@/components/ui/status-badge';
import { ErrorState, LoadingState } from '@/components/ui/states';
import { useMonitor, useSandboxAdvance } from '@/hooks/use-lifecycle';
import { useDemoStatus } from '@/hooks/use-demo';

export function MonitorPage() {
  const { id = '' } = useParams();
  const { data, isLoading, isError, error, refetch } = useMonitor(id);
  const advance = useSandboxAdvance();
  const demo = useDemoStatus();

  if (isLoading) return <LoadingState label="Loading monitor…" />;
  if (isError || !data) {
    return (
      <ErrorState
        title="Unable to load monitor"
        description={error instanceof Error ? error.message : undefined}
        onRetry={() => void refetch()}
      />
    );
  }

  const showAdvance =
    data.canAdvanceSandbox && (demo.data?.sandboxControls ?? true);

  return (
    <div className="mx-auto max-w-[1000px] space-y-8">
      <div className="flex flex-col justify-between gap-4 border-b border-outline-variant pb-6 md:flex-row md:items-end">
        <div>
          <div className="mb-2 flex flex-wrap items-center gap-3">
            <StatusBadge label={data.referenceCode} />
            <StatusBadge label={data.status.replaceAll('_', ' ')} tone="ai" />
            <StatusBadge label="SANDBOX DEMO" tone="warning" />
          </div>
          <h1 className="font-headline text-3xl font-semibold text-primary">
            {data.service.nameEn}
          </h1>
          {data.submissionReference ? (
            <p className="mt-1 text-sm text-on-surface-variant">
              Submission: {data.submissionReference}
            </p>
          ) : null}
        </div>
        <div className="flex flex-wrap gap-3">
          {showAdvance ? (
            <Button
              variant="secondary"
              disabled={advance.isPending}
              onClick={() => void advance.mutateAsync(id).then(() => refetch())}
              aria-label="Advance sandbox status"
            >
              {advance.isPending ? 'Advancing…' : 'Sandbox Advance'}
            </Button>
          ) : null}
          <Link to={`/copilot?transactionId=${encodeURIComponent(data.referenceCode)}`}>
            <Button variant="ai">
              <span className="material-symbols-outlined">smart_toy</span>
              Chat with Copilot
            </Button>
          </Link>
        </div>
      </div>

      <p className="text-sm text-on-surface-variant">{data.disclaimer}</p>
      {showAdvance ? (
        <p className="text-xs text-outline">
          Sandbox Advance simulates progression. No real government processing occurs. Available
          only when DEMO_MODE=true.
        </p>
      ) : null}

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <Card className="glass-panel lg:col-span-2">
          <h2 className="mb-8 flex items-center gap-2 font-headline text-xl text-primary">
            <span className="material-symbols-outlined text-outline">linear_scale</span>
            Transaction Progress
          </h2>
          <TransactionTimeline
            items={data.timeline.map((item) => ({
              title: item.title,
              subtitle: item.subtitle,
              state: item.state,
            }))}
          />
        </Card>

        <div className="space-y-6">
          <Card ai>
            <LogicLabel kind="deterministic" />
            <h3 className="mb-2 mt-2 font-headline text-lg text-primary">
              {data.insight.title}
            </h3>
            <p className="text-sm text-on-surface-variant">{data.insight.summary}</p>
            <p className="mt-3 text-xs text-outline">
              Deterministic sandbox insight — not generated by OpenAI.
            </p>
          </Card>

          <Card>
            <LogicLabel kind="sandbox" />
            <h3 className="mb-3 mt-2 font-headline text-lg text-primary">Payment</h3>
            <p className="text-sm">
              {data.payment.statusLabel} · AED {data.payment.totalAmount.toFixed(2)}
            </p>
            <p className="mt-2 text-xs text-outline">
              Next: {data.estimatedNextStep.replaceAll('_', ' ')}
            </p>
          </Card>
        </div>
      </div>
    </div>
  );
}
